server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: NON_NULL
    serialization.INDENT_OUTPUT: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://${db_ip:localhost}:${db_port:3306}/${db_name:warehouse}?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&jdbcCompliantTruncation=false
    username: ${db_username:root}
    password: ${db_password:123456}
    driver-class: com.mysql.jdbc.Driver

  main:
    banner-mode: off